export enum ErrorType {
  // Common
  INTERNAL_SERVER = 'INTERNAL_SERVER',
  REQUEST_TIMEOUT = 'REQUEST_TIMEOUT',
  NOT_FOUND = 'NOT_FOUND',
  // Auth
  UNAUTHORIZED = 'UNAUTHORIZED',
  INVALID_TOKEN = 'INVALID_TOKEN',
  ACCESS_TOKEN_EXPIRED = 'ACCESS_TOKEN_EXPIRED',
  REFRESH_TOKEN_EXPIRED = 'REFRESH_TOKEN_EXPIRED',
  VERIFY_TOKEN_ERROR = 'VERIFY_TOKEN_ERROR',
  ACTIVATED_EMAIL = 'ACTIVATED_EMAIL',
  BLOCKED_EMAIL = 'BLOCKED_EMAIL',
  // User
  USER_EXISTS = 'USER_EXISTS',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  EMAIL_NOT_FOUND = 'EMAIL_NOT_FOUND',
  EMAIL_NOT_EMPTY = 'EMAIL_NOT_EMPTY',
  VERIFY_CODE_RESET_PASS_NOT_EMPTY = 'VERIFY_CODE_RESET_PASS_NOT_EMPTY',
  CODE_EXPIRED = 'CODE_EXPIRES',
  INVALID_CODE = 'INVALID_CODE',
  VERIFY_CODE_RESET = 'VERIFY_CODE_RESET',
  PHONE_EXISTS = 'PHONE_EXISTS',
  EMAIL_EXISTS = 'EMAIL_EXISTS',
  AVATAR_ID_NOT_FOUND = 'AVARTAR_ID_NOT_FOUND',
  // Role
  ROLE_DOES_NOT_EXISTS = 'ROLE_DOES_NOT_EXISTS',

  BLOCKED_USER = 'BLOCKED_USER',
  INACTIVE_USER = 'INACTIVE_USER',

  PermissionExists = 'PERMISSION_EXISTS',
  RoleExists = 'ROLE_EXISTS',

  InvalidCurrentPassword = 'INVALID_CURRENT_PASSWORD',
  InvalidCredentials = 'INVALID_CREDENTIALS',
  ForeignKeyConflict = 'FOREIGN_KEY_CONFLICT',

  // class
  BASIC_CLASS_EXISTS = 'CLASS_EXISTS',
  CLASS_NAME_NOT_EMPTY = 'CLASS_NAME_NOT_EMPTY',
  CLASS_NAME_MAX_LENGTH = 'CLASS_NAME_MAX_LENGTH',
  CLASS_ORDER_NOT_EMPTY = 'CLASS_ORDER_NOT_EMPTY',
  VALID_NUMBER = 'VALID_NUMBER',
  ID_NOT_EMPTY = 'ID_NOT_EMPTY',
  ID_NOT_FOUND = 'ID_NOT_FOUND',
  // subject
  BASIC_SUBJECT_EXISTS = 'SUBJECT_EXISTS',
  CLASS_NOT_FOUND = 'CLASS_NOT_FOUND',
  INVALID_ACTIVE = 'INVALID_ACTIVE',
  SUBJECT_NAME_NOT_EMPTY = 'SUBJECT_NAME_NOT_EMPTY',
  SUBJECT_NAME_MAX_LENGTH = 'SUBJECT_NAME_MAX_LENGTH',
  ID_ARRAY = 'ID_ARRAY',
  INVALID_ID = 'INVALID_ID',
  ORDER_MUST_NUMBER = 'ORDER_MUST_NUMBER',
  SUBJECT_ID_NOT_FOUND = 'SUBJECT_ID_NOT_FOUND',
  LESSON_CONTENT_NOT_EMPTY = 'LESSON_CONTENT_NOT_EMPTY'
}
